// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendApplicationEvent = `-- name: AppendApplicationEvent :exec
INSERT INTO application_events (id, shelter_id, application_id, type, payload, actor_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendApplicationEventParams struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	ApplicationID uuid.UUID
	Type          string
	Payload       []byte
	ActorUserID   pgtype.UUID
}

// Append-only: there is no update or delete counterpart, because there is no
// grant, no policy and no trigger that would allow one.
func (q *Queries) AppendApplicationEvent(ctx context.Context, arg AppendApplicationEventParams) error {
	_, err := q.db.Exec(ctx, appendApplicationEvent,
		arg.ID,
		arg.ShelterID,
		arg.ApplicationID,
		arg.Type,
		arg.Payload,
		arg.ActorUserID,
	)
	return err
}

const assignApplication = `-- name: AssignApplication :execrows
UPDATE adoption_applications
SET assigned_to_user_id = $2, updated_at = now()
WHERE id = $1
`

type AssignApplicationParams struct {
	ID               uuid.UUID
	AssignedToUserID pgtype.UUID
}

// The assignee must hold a membership in this shelter — enforced by the
// composite key to `memberships (user_id, shelter_id)`, not by this query.
func (q *Queries) AssignApplication(ctx context.Context, arg AssignApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignApplication, arg.ID, arg.AssignedToUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createApplication = `-- name: CreateApplication :one

INSERT INTO adoption_applications (id, shelter_id, pet_id, applicant_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, shelter_id, pet_id, applicant_user_id, status, status_changed_at, assigned_to_user_id, priority_score, decision_note, created_at, updated_at
`

type CreateApplicationParams struct {
	ID              uuid.UUID
	ShelterID       uuid.UUID
	PetID           uuid.UUID
	ApplicantUserID uuid.UUID
}

// The adoption flow: the case, its append-only timeline, and its notes.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (AdoptionApplication, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.ShelterID,
		arg.PetID,
		arg.ApplicantUserID,
	)
	var i AdoptionApplication
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.PetID,
		&i.ApplicantUserID,
		&i.Status,
		&i.StatusChangedAt,
		&i.AssignedToUserID,
		&i.PriorityScore,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const editApplicationNote = `-- name: EditApplicationNote :execrows
UPDATE application_notes
SET body = $2, updated_at = now()
WHERE id = $1
`

type EditApplicationNoteParams struct {
	ID   uuid.UUID
	Body string
}

// A note IS editable, unlike an event. That contrast is the design of 00010.
func (q *Queries) EditApplicationNote(ctx context.Context, arg EditApplicationNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, editApplicationNote, arg.ID, arg.Body)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT id, shelter_id, pet_id, applicant_user_id, status, status_changed_at, assigned_to_user_id, priority_score, decision_note, created_at, updated_at FROM adoption_applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (AdoptionApplication, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i AdoptionApplication
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.PetID,
		&i.ApplicantUserID,
		&i.Status,
		&i.StatusChangedAt,
		&i.AssignedToUserID,
		&i.PriorityScore,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationTimeline = `-- name: ListApplicationTimeline :many
SELECT id, shelter_id, application_id, type, payload, actor_user_id, occurred_at FROM application_events WHERE application_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListApplicationTimeline(ctx context.Context, applicationID uuid.UUID) ([]ApplicationEvent, error) {
	rows, err := q.db.Query(ctx, listApplicationTimeline, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationEvent
	for rows.Next() {
		var i ApplicationEvent
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.ApplicationID,
			&i.Type,
			&i.Payload,
			&i.ActorUserID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByStatus = `-- name: ListApplicationsByStatus :many
SELECT id, shelter_id, pet_id, applicant_user_id, status, status_changed_at, assigned_to_user_id, priority_score, decision_note, created_at, updated_at FROM adoption_applications
WHERE status = $1
ORDER BY created_at DESC
`

// The queue a refuge works from, ordered to match the §4.6 index
// (shelter_id, status, created_at DESC).
func (q *Queries) ListApplicationsByStatus(ctx context.Context, status string) ([]AdoptionApplication, error) {
	rows, err := q.db.Query(ctx, listApplicationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdoptionApplication
	for rows.Next() {
		var i AdoptionApplication
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.PetID,
			&i.ApplicantUserID,
			&i.Status,
			&i.StatusChangedAt,
			&i.AssignedToUserID,
			&i.PriorityScore,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationStatus = `-- name: SetApplicationStatus :execrows
UPDATE adoption_applications
SET status            = $2,
    status_changed_at = now(),
    decision_note     = $3,
    updated_at        = now()
WHERE id = $1
`

type SetApplicationStatusParams struct {
	ID           uuid.UUID
	Status       string
	DecisionNote pgtype.Text
}

// WHICH transitions are legal is decided in the domain layer, not here (LT-4).
// This query moves the status it is given; the caller is what decides whether
// the move was allowed.
func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setApplicationStatus, arg.ID, arg.Status, arg.DecisionNote)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writeApplicationNote = `-- name: WriteApplicationNote :one
INSERT INTO application_notes (id, shelter_id, application_id, author_user_id, body, visibility)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shelter_id, application_id, author_user_id, body, visibility, created_at, updated_at
`

type WriteApplicationNoteParams struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	ApplicationID uuid.UUID
	AuthorUserID  pgtype.UUID
	Body          string
	Visibility    string
}

func (q *Queries) WriteApplicationNote(ctx context.Context, arg WriteApplicationNoteParams) (ApplicationNote, error) {
	row := q.db.QueryRow(ctx, writeApplicationNote,
		arg.ID,
		arg.ShelterID,
		arg.ApplicationID,
		arg.AuthorUserID,
		arg.Body,
		arg.Visibility,
	)
	var i ApplicationNote
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.ApplicationID,
		&i.AuthorUserID,
		&i.Body,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
