// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one

INSERT INTO audit_log (shelter_id, actor_user_id, action, entity_type, entity_id,
                       "before", "after", ip_hash, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type AppendAuditEntryParams struct {
	ShelterID   uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	EntityType  string
	EntityID    pgtype.UUID
	Before      []byte
	After       []byte
	IpHash      pgtype.Text
	UserAgent   pgtype.Text
}

// The forensic trail.
// NO identifier is supplied: `id` is a `bigserial`, and letting the sequence
// issue it is what requires `GRANT USAGE ON SEQUENCE` (T-01-032). A query that
// passed an id would work in every test and fail on the first real write.
func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.ShelterID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.IpHash,
		arg.UserAgent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditEntriesForEntity = `-- name: ListAuditEntriesForEntity :many
SELECT id, shelter_id, actor_user_id, action, entity_type, entity_id, before, after, ip_hash, user_agent, occurred_at FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY occurred_at DESC
`

type ListAuditEntriesForEntityParams struct {
	EntityType string
	EntityID   pgtype.UUID
}

// `entity_type` and `entity_id` are a polymorphic pair with no foreign key, so
// BOTH are needed: an id alone could collide across tables.
func (q *Queries) ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.IpHash,
			&i.UserAgent,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditEntries = `-- name: ListRecentAuditEntries :many
SELECT id, shelter_id, actor_user_id, action, entity_type, entity_id, before, after, ip_hash, user_agent, occurred_at FROM audit_log ORDER BY occurred_at DESC LIMIT $1
`

// Ordered to match the §4.6 index (shelter_id, occurred_at DESC).
func (q *Queries) ListRecentAuditEntries(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAuditEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.IpHash,
			&i.UserAgent,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
