// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one

SELECT id, user_id, token_hash, family_id, expires_at, revoked_at, replaced_by, user_agent, ip_hash, created_at FROM refresh_tokens WHERE token_hash = $1
`

// The auth door's own queries: everything reachable only through app_auth
// (P2-D1..P2-D3, migration 00013). Handlers built later in this phase call
// these inside db.WithAuthUser / db.WithAuthLookup, never inside WithTenant.
//
// Same rule as every other file here: NOT ONE of these filters by
// shelter_id. app_auth cannot even set app.shelter_id -- there is no claim
// yet at this door -- so a query that tried would just be wrong, not merely
// redundant with the policy.
// The rotation lookup (design's rotate flow): parse the cookie's user_id
// prefix, WithAuthUser(userID), then find the presented token by its hash
// inside that scope. token_hash is UNIQUE, so :one is correct.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT id, email, password_hash, status, totp_secret_enc, email_verified_at, created_at
FROM users WHERE email = $1
`

type GetUserCredentialsByEmailRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    pgtype.Text
	Status          string
	TotpSecretEnc   []byte
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

// Only the columns app_auth's SELECT grant carries (P2-D3, 00013). SELECT *
// would name full_name and phone, which app_auth cannot read at all, and the
// statement would fail 42501 before a row ever came back.
func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmail, email)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.TotpSecretEnc,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnMemberships = `-- name: ListOwnMemberships :many
SELECT id, user_id, shelter_id, role, status FROM memberships WHERE user_id = $1
`

type ListOwnMembershipsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ShelterID uuid.UUID
	Role      string
	Status    string
}

// Login needs to know which shelters a user belongs to in order to mint a
// shelter-exchange claim later -- nothing else. Column- and row-scoped to the
// caller (auth_own_memberships, P2-D3): app_auth cannot read another user's
// membership row at all, so no predicate here could leak past the policy.
func (q *Queries) ListOwnMemberships(ctx context.Context, userID uuid.UUID) ([]ListOwnMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listOwnMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnMembershipsRow
	for rows.Next() {
		var i ListOwnMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShelterID,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// Reuse detection revokes the whole family in one statement (§5.2): every
// token sharing family_id, not just the one presented. execrows so a caller
// can tell "revoked N tokens" apart from "the family was already revoked".
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
