// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fileDocument = `-- name: FileDocument :one

INSERT INTO documents (id, shelter_id, media_id, application_id, type, generated_from)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shelter_id, media_id, application_id, type, generated_from, signed_at, signature, created_at
`

type FileDocumentParams struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	MediaID       uuid.UUID
	ApplicationID pgtype.UUID
	Type          string
	GeneratedFrom []byte
}

// Contracts, receipts and certificates.
// `application_id` may be null: a health certificate is filed against an animal
// long before anybody applies for it.
func (q *Queries) FileDocument(ctx context.Context, arg FileDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, fileDocument,
		arg.ID,
		arg.ShelterID,
		arg.MediaID,
		arg.ApplicationID,
		arg.Type,
		arg.GeneratedFrom,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.MediaID,
		&i.ApplicationID,
		&i.Type,
		&i.GeneratedFrom,
		&i.SignedAt,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationDocuments = `-- name: ListApplicationDocuments :many
SELECT id, shelter_id, media_id, application_id, type, generated_from, signed_at, signature, created_at FROM documents WHERE application_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationDocuments(ctx context.Context, applicationID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listApplicationDocuments, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.MediaID,
			&i.ApplicationID,
			&i.Type,
			&i.GeneratedFrom,
			&i.SignedAt,
			&i.Signature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signDocument = `-- name: SignDocument :execrows
UPDATE documents SET signed_at = now(), signature = $2 WHERE id = $1
`

type SignDocumentParams struct {
	ID        uuid.UUID
	Signature []byte
}

func (q *Queries) SignDocument(ctx context.Context, arg SignDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, signDocument, arg.ID, arg.Signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
