// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO form_templates (id, shelter_id, key, name, purpose)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shelter_id, key, name, purpose, is_active, created_at, updated_at
`

type CreateTemplateParams struct {
	ID        uuid.UUID
	ShelterID uuid.UUID
	Key       string
	Name      string
	Purpose   string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (FormTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.ShelterID,
		arg.Key,
		arg.Name,
		arg.Purpose,
	)
	var i FormTemplate
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.Key,
		&i.Name,
		&i.Purpose,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPublishedVersion = `-- name: GetLatestPublishedVersion :one
SELECT id, shelter_id, template_id, version, definition, published_at, created_by, created_at FROM form_template_versions
WHERE template_id = $1 AND published_at IS NOT NULL
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedVersion(ctx context.Context, templateID uuid.UUID) (FormTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedVersion, templateID)
	var i FormTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.TemplateID,
		&i.Version,
		&i.Definition,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateByKey = `-- name: GetTemplateByKey :one

SELECT id, shelter_id, key, name, purpose, is_active, created_at, updated_at FROM form_templates WHERE key = $1 AND is_active
`

// Dynamic forms: templates, immutable versions, and recorded answers.
// `key` is unique PER SHELTER, so under RLS this resolves to exactly one row
// without naming the shelter.
func (q *Queries) GetTemplateByKey(ctx context.Context, key string) (FormTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByKey, key)
	var i FormTemplate
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.Key,
		&i.Name,
		&i.Purpose,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVersionForSubmission = `-- name: GetVersionForSubmission :one
SELECT v.id, v.shelter_id, v.template_id, v.version, v.definition, v.published_at, v.created_by, v.created_at
FROM form_submissions s
JOIN form_template_versions v ON v.id = s.template_version_id
WHERE s.id = $1
`

// The renderer's path, and the reason historical answers stay readable: it
// resolves the version the submission was FILLED WITH, never the latest one.
func (q *Queries) GetVersionForSubmission(ctx context.Context, id uuid.UUID) (FormTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getVersionForSubmission, id)
	var i FormTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.TemplateID,
		&i.Version,
		&i.Definition,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const publishTemplateVersion = `-- name: PublishTemplateVersion :one
INSERT INTO form_template_versions (id, shelter_id, template_id, version,
                                    definition, published_at, created_by)
VALUES ($1, $2, $3, $4, $5, now(), $6)
RETURNING id, shelter_id, template_id, version, definition, published_at, created_by, created_at
`

type PublishTemplateVersionParams struct {
	ID         uuid.UUID
	ShelterID  uuid.UUID
	TemplateID uuid.UUID
	Version    int32
	Definition []byte
	CreatedBy  pgtype.UUID
}

// Publishing APPENDS. There is deliberately no query that updates a published
// version: 00007's trigger refuses it, and a query that tried would be code
// written to be rejected (§4.4 rule 1).
func (q *Queries) PublishTemplateVersion(ctx context.Context, arg PublishTemplateVersionParams) (FormTemplateVersion, error) {
	row := q.db.QueryRow(ctx, publishTemplateVersion,
		arg.ID,
		arg.ShelterID,
		arg.TemplateID,
		arg.Version,
		arg.Definition,
		arg.CreatedBy,
	)
	var i FormTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.TemplateID,
		&i.Version,
		&i.Definition,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const recordSubmission = `-- name: RecordSubmission :one
INSERT INTO form_submissions (id, shelter_id, template_version_id, application_id,
                              submitted_by_user_id, answers, ip_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shelter_id, template_version_id, application_id, submitted_by_user_id, answers, answers_encrypted, submitted_at, ip_hash
`

type RecordSubmissionParams struct {
	ID                uuid.UUID
	ShelterID         uuid.UUID
	TemplateVersionID uuid.UUID
	ApplicationID     pgtype.UUID
	SubmittedByUserID pgtype.UUID
	Answers           []byte
	IpHash            pgtype.Text
}

func (q *Queries) RecordSubmission(ctx context.Context, arg RecordSubmissionParams) (FormSubmission, error) {
	row := q.db.QueryRow(ctx, recordSubmission,
		arg.ID,
		arg.ShelterID,
		arg.TemplateVersionID,
		arg.ApplicationID,
		arg.SubmittedByUserID,
		arg.Answers,
		arg.IpHash,
	)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.TemplateVersionID,
		&i.ApplicationID,
		&i.SubmittedByUserID,
		&i.Answers,
		&i.AnswersEncrypted,
		&i.SubmittedAt,
		&i.IpHash,
	)
	return i, err
}

const searchSubmissions = `-- name: SearchSubmissions :many
SELECT id, shelter_id, template_version_id, application_id, submitted_by_user_id, answers, answers_encrypted, submitted_at, ip_hash FROM form_submissions
WHERE answers @> $1
ORDER BY submitted_at DESC
`

// Containment, which is what the GIN index on `answers` serves. `answers::text
// LIKE` would read the same and use no index at all (§4.6).
func (q *Queries) SearchSubmissions(ctx context.Context, answers []byte) ([]FormSubmission, error) {
	rows, err := q.db.Query(ctx, searchSubmissions, answers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormSubmission
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.TemplateVersionID,
			&i.ApplicationID,
			&i.SubmittedByUserID,
			&i.Answers,
			&i.AnswersEncrypted,
			&i.SubmittedAt,
			&i.IpHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
