// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMedia = `-- name: GetMedia :one
SELECT id, shelter_id, kind, storage_key, mime, bytes, width, height, checksum_sha256, variants, alt_text, uploaded_by, created_at, deleted_at FROM media WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.ChecksumSha256,
		&i.Variants,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const recordUpload = `-- name: RecordUpload :one

INSERT INTO media (id, shelter_id, kind, storage_key, mime, bytes,
                   width, height, checksum_sha256, alt_text, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, shelter_id, kind, storage_key, mime, bytes, width, height, checksum_sha256, variants, alt_text, uploaded_by, created_at, deleted_at
`

type RecordUploadParams struct {
	ID             uuid.UUID
	ShelterID      uuid.UUID
	Kind           string
	StorageKey     string
	Mime           string
	Bytes          int64
	Width          pgtype.Int4
	Height         pgtype.Int4
	ChecksumSha256 []byte
	AltText        pgtype.Text
	UploadedBy     pgtype.UUID
}

// Uploaded files. The bytes live in R2 (§5.5); this is the record of them.
func (q *Queries) RecordUpload(ctx context.Context, arg RecordUploadParams) (Medium, error) {
	row := q.db.QueryRow(ctx, recordUpload,
		arg.ID,
		arg.ShelterID,
		arg.Kind,
		arg.StorageKey,
		arg.Mime,
		arg.Bytes,
		arg.Width,
		arg.Height,
		arg.ChecksumSha256,
		arg.AltText,
		arg.UploadedBy,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.ChecksumSha256,
		&i.Variants,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :execrows
UPDATE media SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

// Soft, because `pet_media` and `documents` reference it with RESTRICT and a
// hard delete would be refused by whichever one points at it.
func (q *Queries) SoftDeleteMedia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
