// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdoptionApplication struct {
	ID               uuid.UUID
	ShelterID        uuid.UUID
	PetID            uuid.UUID
	ApplicantUserID  uuid.UUID
	Status           string
	StatusChangedAt  pgtype.Timestamptz
	AssignedToUserID pgtype.UUID
	PriorityScore    pgtype.Int4
	DecisionNote     pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ApplicationEvent struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	ApplicationID uuid.UUID
	Type          string
	Payload       []byte
	ActorUserID   pgtype.UUID
	OccurredAt    pgtype.Timestamptz
}

type ApplicationNote struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	ApplicationID uuid.UUID
	AuthorUserID  pgtype.UUID
	Body          string
	Visibility    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	ShelterID   uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	EntityType  string
	EntityID    pgtype.UUID
	Before      []byte
	After       []byte
	IpHash      pgtype.Text
	UserAgent   pgtype.Text
	OccurredAt  pgtype.Timestamptz
}

type Breed struct {
	ID        uuid.UUID
	SpeciesID uuid.UUID
	Name      string
}

type Document struct {
	ID            uuid.UUID
	ShelterID     uuid.UUID
	MediaID       uuid.UUID
	ApplicationID pgtype.UUID
	Type          string
	GeneratedFrom []byte
	SignedAt      pgtype.Timestamptz
	Signature     []byte
	CreatedAt     pgtype.Timestamptz
}

type FormSubmission struct {
	ID                uuid.UUID
	ShelterID         uuid.UUID
	TemplateVersionID uuid.UUID
	ApplicationID     pgtype.UUID
	SubmittedByUserID pgtype.UUID
	Answers           []byte
	AnswersEncrypted  []byte
	SubmittedAt       pgtype.Timestamptz
	IpHash            pgtype.Text
}

type FormTemplate struct {
	ID        uuid.UUID
	ShelterID uuid.UUID
	Key       string
	Name      string
	Purpose   string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FormTemplateVersion struct {
	ID          uuid.UUID
	ShelterID   uuid.UUID
	TemplateID  uuid.UUID
	Version     int32
	Definition  []byte
	PublishedAt pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Medium struct {
	ID             uuid.UUID
	ShelterID      uuid.UUID
	Kind           string
	StorageKey     string
	Mime           string
	Bytes          int64
	Width          pgtype.Int4
	Height         pgtype.Int4
	ChecksumSha256 []byte
	Variants       []byte
	AltText        pgtype.Text
	UploadedBy     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Membership struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ShelterID  uuid.UUID
	Role       string
	Status     string
	InvitedBy  pgtype.UUID
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Pet struct {
	ID                  uuid.UUID
	ShelterID           uuid.UUID
	PublicCode          string
	Name                string
	SpeciesID           uuid.UUID
	BreedID             pgtype.UUID
	BreedNote           pgtype.Text
	Sex                 string
	Size                string
	BirthDateEstimate   pgtype.Date
	AgePrecision        string
	WeightKg            pgtype.Numeric
	Status              string
	StatusChangedAt     pgtype.Timestamptz
	Sterilized          pgtype.Bool
	Vaccinated          pgtype.Bool
	Dewormed            pgtype.Bool
	MicrochipID         pgtype.Text
	EnergyLevel         string
	GoodWithKids        string
	GoodWithDogs        string
	GoodWithCats        string
	SpecialNeeds        bool
	SpecialNeedsNote    pgtype.Text
	Story               pgtype.Text
	Description         pgtype.Text
	IntakeDate          pgtype.Date
	IntakeReason        pgtype.Text
	AdoptionFeeCents    int32
	AdoptionFeeCurrency string
	PublishedAt         pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type PetHealthRecord struct {
	ID              uuid.UUID
	ShelterID       uuid.UUID
	PetID           uuid.UUID
	Type            string
	OccurredOn      pgtype.Date
	Description     pgtype.Text
	VetName         pgtype.Text
	DocumentMediaID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PetMedium struct {
	PetID     uuid.UUID
	MediaID   uuid.UUID
	ShelterID uuid.UUID
	Position  int32
	IsPrimary bool
	CreatedAt pgtype.Timestamptz
}

type PetStatusHistory struct {
	ID          uuid.UUID
	ShelterID   uuid.UUID
	PetID       uuid.UUID
	FromStatus  pgtype.Text
	ToStatus    string
	Reason      pgtype.Text
	ActorUserID pgtype.UUID
	OccurredAt  pgtype.Timestamptz
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	FamilyID   uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.UUID
	UserAgent  pgtype.Text
	IpHash     []byte
	CreatedAt  pgtype.Timestamptz
}

type Shelter struct {
	ID                uuid.UUID
	Slug              string
	LegalName         pgtype.Text
	DisplayName       string
	Country           pgtype.Text
	State             pgtype.Text
	City              pgtype.Text
	Status            string
	VerifiedAt        pgtype.Timestamptz
	VerifiedBy        pgtype.UUID
	Mission           pgtype.Text
	Vision            pgtype.Text
	About             pgtype.Text
	LogoMediaID       pgtype.UUID
	CoverMediaID      pgtype.UUID
	ContactEmail      pgtype.Text
	ContactPhone      pgtype.Text
	Website           pgtype.Text
	Socials           []byte
	DonationLinks     []byte
	StorageBytesUsed  int64
	StorageQuotaBytes int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Species struct {
	ID   uuid.UUID
	Code string
	Name string
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    pgtype.Text
	FullName        pgtype.Text
	Phone           pgtype.Text
	Status          string
	EmailVerifiedAt pgtype.Timestamptz
	TotpSecretEnc   []byte
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
