// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendStatusChange = `-- name: AppendStatusChange :exec
INSERT INTO pet_status_history (id, shelter_id, pet_id, from_status, to_status,
                                reason, actor_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AppendStatusChangeParams struct {
	ID          uuid.UUID
	ShelterID   uuid.UUID
	PetID       uuid.UUID
	FromStatus  pgtype.Text
	ToStatus    string
	Reason      pgtype.Text
	ActorUserID pgtype.UUID
}

// `pet_status_history` is append-only (LT-5): insert and select, nothing else.
// There is no update or delete query here because there is no grant for one.
func (q *Queries) AppendStatusChange(ctx context.Context, arg AppendStatusChangeParams) error {
	_, err := q.db.Exec(ctx, appendStatusChange,
		arg.ID,
		arg.ShelterID,
		arg.PetID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ActorUserID,
	)
	return err
}

const attachPhoto = `-- name: AttachPhoto :exec
INSERT INTO pet_media (pet_id, media_id, shelter_id, position, is_primary)
VALUES ($1, $2, $3, $4, $5)
`

type AttachPhotoParams struct {
	PetID     uuid.UUID
	MediaID   uuid.UUID
	ShelterID uuid.UUID
	Position  int32
	IsPrimary bool
}

func (q *Queries) AttachPhoto(ctx context.Context, arg AttachPhotoParams) error {
	_, err := q.db.Exec(ctx, attachPhoto,
		arg.PetID,
		arg.MediaID,
		arg.ShelterID,
		arg.Position,
		arg.IsPrimary,
	)
	return err
}

const createPet = `-- name: CreatePet :one

INSERT INTO pets (id, shelter_id, public_code, name, species_id, breed_id, sex, size,
                  energy_level, good_with_kids, good_with_dogs, good_with_cats,
                  description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, shelter_id, public_code, name, species_id, breed_id, breed_note, sex, size, birth_date_estimate, age_precision, weight_kg, status, status_changed_at, sterilized, vaccinated, dewormed, microchip_id, energy_level, good_with_kids, good_with_dogs, good_with_cats, special_needs, special_needs_note, story, description, intake_date, intake_reason, adoption_fee_cents, adoption_fee_currency, published_at, created_by, created_at, updated_at, deleted_at
`

type CreatePetParams struct {
	ID           uuid.UUID
	ShelterID    uuid.UUID
	PublicCode   string
	Name         string
	SpeciesID    uuid.UUID
	BreedID      pgtype.UUID
	Sex          string
	Size         string
	EnergyLevel  string
	GoodWithKids string
	GoodWithDogs string
	GoodWithCats string
	Description  pgtype.Text
	CreatedBy    pgtype.UUID
}

// The catalog core and its three children.
func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.ID,
		arg.ShelterID,
		arg.PublicCode,
		arg.Name,
		arg.SpeciesID,
		arg.BreedID,
		arg.Sex,
		arg.Size,
		arg.EnergyLevel,
		arg.GoodWithKids,
		arg.GoodWithDogs,
		arg.GoodWithCats,
		arg.Description,
		arg.CreatedBy,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.PublicCode,
		&i.Name,
		&i.SpeciesID,
		&i.BreedID,
		&i.BreedNote,
		&i.Sex,
		&i.Size,
		&i.BirthDateEstimate,
		&i.AgePrecision,
		&i.WeightKg,
		&i.Status,
		&i.StatusChangedAt,
		&i.Sterilized,
		&i.Vaccinated,
		&i.Dewormed,
		&i.MicrochipID,
		&i.EnergyLevel,
		&i.GoodWithKids,
		&i.GoodWithDogs,
		&i.GoodWithCats,
		&i.SpecialNeeds,
		&i.SpecialNeedsNote,
		&i.Story,
		&i.Description,
		&i.IntakeDate,
		&i.IntakeReason,
		&i.AdoptionFeeCents,
		&i.AdoptionFeeCurrency,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPet = `-- name: GetPet :one
SELECT id, shelter_id, public_code, name, species_id, breed_id, breed_note, sex, size, birth_date_estimate, age_precision, weight_kg, status, status_changed_at, sterilized, vaccinated, dewormed, microchip_id, energy_level, good_with_kids, good_with_dogs, good_with_cats, special_needs, special_needs_note, story, description, intake_date, intake_reason, adoption_fee_cents, adoption_fee_currency, published_at, created_by, created_at, updated_at, deleted_at FROM pets WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPet(ctx context.Context, id uuid.UUID) (Pet, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.PublicCode,
		&i.Name,
		&i.SpeciesID,
		&i.BreedID,
		&i.BreedNote,
		&i.Sex,
		&i.Size,
		&i.BirthDateEstimate,
		&i.AgePrecision,
		&i.WeightKg,
		&i.Status,
		&i.StatusChangedAt,
		&i.Sterilized,
		&i.Vaccinated,
		&i.Dewormed,
		&i.MicrochipID,
		&i.EnergyLevel,
		&i.GoodWithKids,
		&i.GoodWithDogs,
		&i.GoodWithCats,
		&i.SpecialNeeds,
		&i.SpecialNeedsNote,
		&i.Story,
		&i.Description,
		&i.IntakeDate,
		&i.IntakeReason,
		&i.AdoptionFeeCents,
		&i.AdoptionFeeCurrency,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPetsByStatus = `-- name: ListPetsByStatus :many
SELECT id, shelter_id, public_code, name, species_id, breed_id, breed_note, sex, size, birth_date_estimate, age_precision, weight_kg, status, status_changed_at, sterilized, vaccinated, dewormed, microchip_id, energy_level, good_with_kids, good_with_dogs, good_with_cats, special_needs, special_needs_note, story, description, intake_date, intake_reason, adoption_fee_cents, adoption_fee_currency, published_at, created_by, created_at, updated_at, deleted_at FROM pets
WHERE status = $1 AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST
`

// The shelter dashboard read, ordered to match the §4.6 index
// (shelter_id, status, published_at DESC) so the plan can walk it.
func (q *Queries) ListPetsByStatus(ctx context.Context, status string) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listPetsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.PublicCode,
			&i.Name,
			&i.SpeciesID,
			&i.BreedID,
			&i.BreedNote,
			&i.Sex,
			&i.Size,
			&i.BirthDateEstimate,
			&i.AgePrecision,
			&i.WeightKg,
			&i.Status,
			&i.StatusChangedAt,
			&i.Sterilized,
			&i.Vaccinated,
			&i.Dewormed,
			&i.MicrochipID,
			&i.EnergyLevel,
			&i.GoodWithKids,
			&i.GoodWithDogs,
			&i.GoodWithCats,
			&i.SpecialNeeds,
			&i.SpecialNeedsNote,
			&i.Story,
			&i.Description,
			&i.IntakeDate,
			&i.IntakeReason,
			&i.AdoptionFeeCents,
			&i.AdoptionFeeCurrency,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusHistory = `-- name: ListStatusHistory :many
SELECT id, shelter_id, pet_id, from_status, to_status, reason, actor_user_id, occurred_at FROM pet_status_history WHERE pet_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListStatusHistory(ctx context.Context, petID uuid.UUID) ([]PetStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistory, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PetStatusHistory
	for rows.Next() {
		var i PetStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ShelterID,
			&i.PetID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ActorUserID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPet = `-- name: PublishPet :execrows
UPDATE pets
SET status            = 'available',
    published_at      = coalesce(published_at, now()),
    status_changed_at = now(),
    updated_at        = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) PublishPet(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, publishPet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordHealthEvent = `-- name: RecordHealthEvent :one
INSERT INTO pet_health_records (id, shelter_id, pet_id, type, occurred_on,
                                description, vet_name, document_media_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shelter_id, pet_id, type, occurred_on, description, vet_name, document_media_id, created_at, updated_at
`

type RecordHealthEventParams struct {
	ID              uuid.UUID
	ShelterID       uuid.UUID
	PetID           uuid.UUID
	Type            string
	OccurredOn      pgtype.Date
	Description     pgtype.Text
	VetName         pgtype.Text
	DocumentMediaID pgtype.UUID
}

func (q *Queries) RecordHealthEvent(ctx context.Context, arg RecordHealthEventParams) (PetHealthRecord, error) {
	row := q.db.QueryRow(ctx, recordHealthEvent,
		arg.ID,
		arg.ShelterID,
		arg.PetID,
		arg.Type,
		arg.OccurredOn,
		arg.Description,
		arg.VetName,
		arg.DocumentMediaID,
	)
	var i PetHealthRecord
	err := row.Scan(
		&i.ID,
		&i.ShelterID,
		&i.PetID,
		&i.Type,
		&i.OccurredOn,
		&i.Description,
		&i.VetName,
		&i.DocumentMediaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
