// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Append-only: there is no update or delete counterpart, because there is no
	// grant, no policy and no trigger that would allow one.
	AppendApplicationEvent(ctx context.Context, arg AppendApplicationEventParams) error
	// The forensic trail.
	// NO identifier is supplied: `id` is a `bigserial`, and letting the sequence
	// issue it is what requires `GRANT USAGE ON SEQUENCE` (T-01-032). A query that
	// passed an id would work in every test and fail on the first real write.
	AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (int64, error)
	// `pet_status_history` is append-only (LT-5): insert and select, nothing else.
	// There is no update or delete query here because there is no grant for one.
	AppendStatusChange(ctx context.Context, arg AppendStatusChangeParams) error
	// The assignee must hold a membership in this shelter — enforced by the
	// composite key to `memberships (user_id, shelter_id)`, not by this query.
	AssignApplication(ctx context.Context, arg AssignApplicationParams) (int64, error)
	AttachPhoto(ctx context.Context, arg AttachPhotoParams) error
	// The adoption flow: the case, its append-only timeline, and its notes.
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (AdoptionApplication, error)
	// The catalog core and its three children.
	CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (FormTemplate, error)
	// A note IS editable, unlike an event. That contrast is the design of 00010.
	EditApplicationNote(ctx context.Context, arg EditApplicationNoteParams) (int64, error)
	// Contracts, receipts and certificates.
	// `application_id` may be null: a health certificate is filed against an animal
	// long before anybody applies for it.
	FileDocument(ctx context.Context, arg FileDocumentParams) (Document, error)
	GetApplication(ctx context.Context, id uuid.UUID) (AdoptionApplication, error)
	// Tenancy and identity.
	//
	// NOT ONE of these reads filters by `shelter_id`, and that is deliberate rather
	// than an omission: the policy does it. A query that filtered too would return
	// the same rows whether or not the policy existed, which is how the loss of a
	// policy becomes invisible (§3 layer 3).
	// The tenant's own row. No predicate at all: under RLS this is the only row
	// `shelters` has for this transaction, which is the property the A/B suite pins.
	GetCurrentShelter(ctx context.Context) (Shelter, error)
	GetLatestPublishedVersion(ctx context.Context, templateID uuid.UUID) (FormTemplateVersion, error)
	GetMedia(ctx context.Context, id uuid.UUID) (Medium, error)
	GetPet(ctx context.Context, id uuid.UUID) (Pet, error)
	// Dynamic forms: templates, immutable versions, and recorded answers.
	// `key` is unique PER SHELTER, so under RLS this resolves to exactly one row
	// without naming the shelter.
	GetTemplateByKey(ctx context.Context, key string) (FormTemplate, error)
	// Users and memberships.
	//
	// `users` is the one table in this schema that belongs to no shelter (D6), so
	// its visibility comes from a policy that reads `memberships` and, since 00009,
	// `adoption_applications`. A caller sees exactly the users those two branches
	// allow — nothing here narrows it further.
	// `email` is `citext`, so this finds a differently-cased address without the
	// call site remembering to normalise (D7).
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// The renderer's path, and the reason historical answers stay readable: it
	// resolves the version the submission was FILLED WITH, never the latest one.
	GetVersionForSubmission(ctx context.Context, id uuid.UUID) (FormTemplateVersion, error)
	// Supplying `shelter_id` is not filtering by it: the column is NOT NULL and
	// `WITH CHECK` is what verifies the value.
	InviteMember(ctx context.Context, arg InviteMemberParams) error
	ListApplicationDocuments(ctx context.Context, applicationID pgtype.UUID) ([]Document, error)
	ListApplicationTimeline(ctx context.Context, applicationID uuid.UUID) ([]ApplicationEvent, error)
	// The queue a refuge works from, ordered to match the §4.6 index
	// (shelter_id, status, created_at DESC).
	ListApplicationsByStatus(ctx context.Context, status string) ([]AdoptionApplication, error)
	// `entity_type` and `entity_id` are a polymorphic pair with no foreign key, so
	// BOTH are needed: an id alone could collide across tables.
	ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error)
	// `breeds` carries no `shelter_id` at all, so `species_id` is a domain filter
	// rather than a tenant one.
	ListBreedsForSpecies(ctx context.Context, speciesID uuid.UUID) ([]Breed, error)
	// The shelter dashboard read, ordered to match the §4.6 index
	// (shelter_id, status, published_at DESC) so the plan can walk it.
	ListPetsByStatus(ctx context.Context, status string) ([]Pet, error)
	// Ordered to match the §4.6 index (shelter_id, occurred_at DESC).
	ListRecentAuditEntries(ctx context.Context, limit int32) ([]AuditLog, error)
	// The staff of the current shelter. `memberships` is tenant-scoped, so the join
	// is already narrowed to this tenant without a predicate here.
	ListShelterMembers(ctx context.Context) ([]ListShelterMembersRow, error)
	// Global reference data: readable by both roles, writable by neither.
	ListSpecies(ctx context.Context) ([]Species, error)
	ListStatusHistory(ctx context.Context, petID uuid.UUID) ([]PetStatusHistory, error)
	PublishPet(ctx context.Context, id uuid.UUID) (int64, error)
	// Publishing APPENDS. There is deliberately no query that updates a published
	// version: 00007's trigger refuses it, and a query that tried would be code
	// written to be rejected (§4.4 rule 1).
	PublishTemplateVersion(ctx context.Context, arg PublishTemplateVersionParams) (FormTemplateVersion, error)
	RecordHealthEvent(ctx context.Context, arg RecordHealthEventParams) (PetHealthRecord, error)
	RecordSubmission(ctx context.Context, arg RecordSubmissionParams) (FormSubmission, error)
	// Uploaded files. The bytes live in R2 (§5.5); this is the record of them.
	RecordUpload(ctx context.Context, arg RecordUploadParams) (Medium, error)
	// Containment, which is what the GIN index on `answers` serves. `answers::text
	// LIKE` would read the same and use no index at all (§4.6).
	SearchSubmissions(ctx context.Context, answers []byte) ([]FormSubmission, error)
	// WHICH transitions are legal is decided in the domain layer, not here (LT-4).
	// This query moves the status it is given; the caller is what decides whether
	// the move was allowed.
	SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (int64, error)
	SignDocument(ctx context.Context, arg SignDocumentParams) (int64, error)
	// Soft, because `pet_media` and `documents` reference it with RESTRICT and a
	// hard delete would be refused by whichever one points at it.
	SoftDeleteMedia(ctx context.Context, id uuid.UUID) (int64, error)
	// The institutional profile of §4.1. `execrows` rather than `exec`: a policy
	// that filtered the row away reports zero rows, and callers have to be able to
	// tell that apart from a successful write.
	UpdateShelterProfile(ctx context.Context, arg UpdateShelterProfileParams) (int64, error)
	WriteApplicationNote(ctx context.Context, arg WriteApplicationNoteParams) (ApplicationNote, error)
}

var _ Querier = (*Queries)(nil)
