// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Append-only: there is no update or delete counterpart, because there is no
	// grant, no policy and no trigger that would allow one.
	AppendApplicationEvent(ctx context.Context, arg AppendApplicationEventParams) error
	// The forensic trail.
	// NO identifier is supplied: `id` is a `bigserial`, and letting the sequence
	// issue it is what requires `GRANT USAGE ON SEQUENCE` (T-01-032). A query that
	// passed an id would work in every test and fail on the first real write.
	AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (int64, error)
	// `pet_status_history` is append-only (LT-5): insert and select, nothing else.
	// There is no update or delete query here because there is no grant for one.
	AppendStatusChange(ctx context.Context, arg AppendStatusChangeParams) error
	// The assignee must hold a membership in this shelter — enforced by the
	// composite key to `memberships (user_id, shelter_id)`, not by this query.
	AssignApplication(ctx context.Context, arg AssignApplicationParams) (int64, error)
	AttachPhoto(ctx context.Context, arg AttachPhotoParams) error
	// The adoption flow: the case, its append-only timeline, and its notes.
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (AdoptionApplication, error)
	// The catalog core and its three children.
	CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (FormTemplate, error)
	// Regeneration starts by clearing the previous set, all ten in one
	// statement, in the same transaction as the ten inserts above.
	DeleteRecoveryCodesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// A note IS editable, unlike an event. That contrast is the design of 00010.
	EditApplicationNote(ctx context.Context, arg EditApplicationNoteParams) (int64, error)
	// Contracts, receipts and certificates.
	// `application_id` may be null: a health certificate is filed against an animal
	// long before anybody applies for it.
	FileDocument(ctx context.Context, arg FileDocumentParams) (Document, error)
	GetApplication(ctx context.Context, id uuid.UUID) (AdoptionApplication, error)
	// Tenancy and identity.
	//
	// NOT ONE of these reads filters by `shelter_id`, and that is deliberate rather
	// than an omission: the policy does it. A query that filtered too would return
	// the same rows whether or not the policy existed, which is how the loss of a
	// policy becomes invisible (§3 layer 3).
	// The tenant's own row. No predicate at all: under RLS this is the only row
	// `shelters` has for this transaction, which is the property the A/B suite pins.
	GetCurrentShelter(ctx context.Context) (Shelter, error)
	GetLatestPublishedVersion(ctx context.Context, templateID uuid.UUID) (FormTemplateVersion, error)
	GetMedia(ctx context.Context, id uuid.UUID) (Medium, error)
	GetPet(ctx context.Context, id uuid.UUID) (Pet, error)
	// The redemption lookup: parse the submitted code, hash it, find the row.
	// code_hash is UNIQUE, so :one is correct.
	GetRecoveryCodeByHash(ctx context.Context, codeHash []byte) (TotpRecoveryCode, error)
	// The auth door's own queries: everything reachable only through app_auth
	// (P2-D1..P2-D3, migration 00013). Handlers built later in this phase call
	// these inside db.WithAuthUser / db.WithAuthLookup, never inside WithTenant.
	//
	// Same rule as every other file here: NOT ONE of these filters by
	// shelter_id. app_auth cannot even set app.shelter_id -- there is no claim
	// yet at this door -- so a query that tried would just be wrong, not merely
	// redundant with the policy.
	// The rotation lookup (design's rotate flow): parse the cookie's user_id
	// prefix, WithAuthUser(userID), then find the presented token by its hash
	// inside that scope. token_hash is UNIQUE, so :one is correct.
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Dynamic forms: templates, immutable versions, and recorded answers.
	// `key` is unique PER SHELTER, so under RLS this resolves to exactly one row
	// without naming the shelter.
	GetTemplateByKey(ctx context.Context, key string) (FormTemplate, error)
	// Users and memberships.
	//
	// `users` is the one table in this schema that belongs to no shelter (D6), so
	// its visibility comes from a policy that reads `memberships` and, since 00009,
	// `adoption_applications`. A caller sees exactly the users those two branches
	// allow — nothing here narrows it further.
	// `email` is `citext`, so this finds a differently-cased address without the
	// call site remembering to normalise (D7).
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Only the columns app_auth's SELECT grant carries (P2-D3, 00013). SELECT *
	// would name full_name and phone, which app_auth cannot read at all, and the
	// statement would fail 42501 before a row ever came back.
	GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error)
	// The renderer's path, and the reason historical answers stay readable: it
	// resolves the version the submission was FILLED WITH, never the latest one.
	GetVersionForSubmission(ctx context.Context, id uuid.UUID) (FormTemplateVersion, error)
	// totp_recovery_codes (P2-D8, migration 00014). The regeneration flow
	// (T-02-017/018) issues DeleteRecoveryCodesForUser once and InsertRecoveryCode
	// ten times inside one WithAuthUser transaction; SELECT/DELETE carry a table
	// grant, INSERT the same, and UPDATE is column-scoped to used_at only -- code_hash
	// and created_at are never rewritten once a row exists.
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	// Both halves of a session's life: login starts a family by passing a fresh
	// family_id, rotation continues one by passing the presented token's. The
	// caller chooses, because only the caller knows which of the two it is --
	// a default here would silently make every rotation start a new family and
	// quietly disable family-wide revocation.
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	// Supplying `shelter_id` is not filtering by it: the column is NOT NULL and
	// `WITH CHECK` is what verifies the value.
	InviteMember(ctx context.Context, arg InviteMemberParams) error
	ListApplicationDocuments(ctx context.Context, applicationID pgtype.UUID) ([]Document, error)
	ListApplicationTimeline(ctx context.Context, applicationID uuid.UUID) ([]ApplicationEvent, error)
	// The queue a refuge works from, ordered to match the §4.6 index
	// (shelter_id, status, created_at DESC).
	ListApplicationsByStatus(ctx context.Context, status string) ([]AdoptionApplication, error)
	// `entity_type` and `entity_id` are a polymorphic pair with no foreign key, so
	// BOTH are needed: an id alone could collide across tables.
	ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error)
	// `breeds` carries no `shelter_id` at all, so `species_id` is a domain filter
	// rather than a tenant one.
	ListBreedsForSpecies(ctx context.Context, speciesID uuid.UUID) ([]Breed, error)
	// Login needs to know which shelters a user belongs to in order to mint a
	// shelter-exchange claim later -- nothing else. Column- and row-scoped to the
	// caller (auth_own_memberships, P2-D3): app_auth cannot read another user's
	// membership row at all, so no predicate here could leak past the policy.
	ListOwnMemberships(ctx context.Context, userID uuid.UUID) ([]ListOwnMembershipsRow, error)
	// The shelter dashboard read, ordered to match the §4.6 index
	// (shelter_id, status, published_at DESC) so the plan can walk it.
	ListPetsByStatus(ctx context.Context, status string) ([]Pet, error)
	// Ordered to match the §4.6 index (shelter_id, occurred_at DESC).
	ListRecentAuditEntries(ctx context.Context, limit int32) ([]AuditLog, error)
	// The staff of the current shelter. `memberships` is tenant-scoped, so the join
	// is already narrowed to this tenant without a predicate here.
	ListShelterMembers(ctx context.Context) ([]ListShelterMembersRow, error)
	// Global reference data: readable by both roles, writable by neither.
	ListSpecies(ctx context.Context) ([]Species, error)
	ListStatusHistory(ctx context.Context, petID uuid.UUID) ([]PetStatusHistory, error)
	// Serialises every transaction that touches one session family.
	//
	// This exists because READ COMMITTED alone cannot give the family-revocation
	// guarantee. `RevokeRefreshTokenFamily` below fixes its candidate rows at the
	// snapshot its own statement takes; a successor row that a CONCURRENT rotation
	// inserts afterwards is never in that set and survives the revocation of its
	// own family -- permanently, because nothing revokes an already-revoked family
	// a second time. Judgment Day (T-02-021) found it and a concurrency test
	// reproduces it.
	//
	// Taken after the presented row is read, because the family_id is not known
	// before that. Once it is held, no other transaction can begin deciding this
	// family until this one ends, so a concurrent revocation either already
	// committed (and RevokeRefreshTokenIfLive below then matches zero rows and the
	// rotation is refused) or cannot start until the successor row is committed and
	// therefore visible to it.
	//
	// `xact` means it releases at COMMIT or ROLLBACK, so no path can leak it.
	//
	// A hash collision between two different family_ids costs concurrency, never
	// correctness: the two families would serialise against each other for no
	// reason, and both still behave correctly.
	LockRefreshTokenFamily(ctx context.Context, dollar_1 string) error
	PublishPet(ctx context.Context, id uuid.UUID) (int64, error)
	// Publishing APPENDS. There is deliberately no query that updates a published
	// version: 00007's trigger refuses it, and a query that tried would be code
	// written to be rejected (§4.4 rule 1).
	PublishTemplateVersion(ctx context.Context, arg PublishTemplateVersionParams) (FormTemplateVersion, error)
	RecordHealthEvent(ctx context.Context, arg RecordHealthEventParams) (PetHealthRecord, error)
	RecordSubmission(ctx context.Context, arg RecordSubmissionParams) (FormSubmission, error)
	// Uploaded files. The bytes live in R2 (§5.5); this is the record of them.
	RecordUpload(ctx context.Context, arg RecordUploadParams) (Medium, error)
	// Single-use redemption: only a row with used_at still null is matched, so a
	// repeated or concurrent redemption of the same code affects zero rows --
	// the same "qualified write, zero rows means refused" shape
	// RevokeRefreshTokenFamily above uses for its own idempotency question.
	RedeemRecoveryCode(ctx context.Context, codeHash []byte) (int64, error)
	// Reuse detection revokes the whole family in one statement (§5.2): every
	// token sharing family_id, not just the one presented. execrows so a caller
	// can tell "revoked N tokens" apart from "the family was already revoked".
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) (int64, error)
	// The FIRST half of a rotation's write, and now the only one that revokes
	// anything (00017 split what used to be one statement, MarkRefreshTokenRotated,
	// into this and SetRefreshTokenReplacedBy below).
	//
	// This runs BEFORE the successor is inserted, not after: 00017 adds a unique
	// index enforcing at most one live row per family_id, and the old
	// insert-then-mark order would transiently hold the presented token AND its
	// successor live at once, which that index now refuses.
	//
	// `revoked_at IS NULL` is a guard, not decoration: it makes this the write
	// that loses a concurrent race. Two simultaneous rotations of the same
	// token both read a live row, and only one can affect a row here -- the
	// other gets zero and is refused, instead of both minting a session.
	RevokeRefreshTokenIfLive(ctx context.Context, id uuid.UUID) (int64, error)
	// Containment, which is what the GIN index on `answers` serves. `answers::text
	// LIKE` would read the same and use no index at all (§4.6).
	SearchSubmissions(ctx context.Context, answers []byte) ([]FormSubmission, error)
	// WHICH transitions are legal is decided in the domain layer, not here (LT-4).
	// This query moves the status it is given; the caller is what decides whether
	// the move was allowed.
	SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (int64, error)
	// The SECOND half: the back-pointer can only be set once the successor row
	// exists, because replaced_by is a foreign key into this same table. Split
	// off from the revoke above so the revoke can run first -- see the note
	// there.
	SetRefreshTokenReplacedBy(ctx context.Context, arg SetRefreshTokenReplacedByParams) error
	SignDocument(ctx context.Context, arg SignDocumentParams) (int64, error)
	// Soft, because `pet_media` and `documents` reference it with RESTRICT and a
	// hard delete would be refused by whichever one points at it.
	SoftDeleteMedia(ctx context.Context, id uuid.UUID) (int64, error)
	// The institutional profile of §4.1. `execrows` rather than `exec`: a policy
	// that filtered the row away reports zero rows, and callers have to be able to
	// tell that apart from a successful write.
	UpdateShelterProfile(ctx context.Context, arg UpdateShelterProfileParams) (int64, error)
	WriteApplicationNote(ctx context.Context, arg WriteApplicationNoteParams) (ApplicationNote, error)
}

var _ Querier = (*Queries)(nil)
