// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listBreedsForSpecies = `-- name: ListBreedsForSpecies :many
SELECT id, species_id, name FROM breeds WHERE species_id = $1 ORDER BY name
`

// `breeds` carries no `shelter_id` at all, so `species_id` is a domain filter
// rather than a tenant one.
func (q *Queries) ListBreedsForSpecies(ctx context.Context, speciesID uuid.UUID) ([]Breed, error) {
	rows, err := q.db.Query(ctx, listBreedsForSpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Breed
	for rows.Next() {
		var i Breed
		if err := rows.Scan(&i.ID, &i.SpeciesID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecies = `-- name: ListSpecies :many

SELECT id, code, name FROM species ORDER BY name
`

// Global reference data: readable by both roles, writable by neither.
func (q *Queries) ListSpecies(ctx context.Context) ([]Species, error) {
	rows, err := q.db.Query(ctx, listSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Species
	for rows.Next() {
		var i Species
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
