// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shelters.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentShelter = `-- name: GetCurrentShelter :one

SELECT id, slug, legal_name, display_name, country, state, city, status, verified_at, verified_by, mission, vision, about, logo_media_id, cover_media_id, contact_email, contact_phone, website, socials, donation_links, storage_bytes_used, storage_quota_bytes, created_at, updated_at FROM shelters LIMIT 1
`

// Tenancy and identity.
//
// NOT ONE of these reads filters by `shelter_id`, and that is deliberate rather
// than an omission: the policy does it. A query that filtered too would return
// the same rows whether or not the policy existed, which is how the loss of a
// policy becomes invisible (§3 layer 3).
// The tenant's own row. No predicate at all: under RLS this is the only row
// `shelters` has for this transaction, which is the property the A/B suite pins.
func (q *Queries) GetCurrentShelter(ctx context.Context) (Shelter, error) {
	row := q.db.QueryRow(ctx, getCurrentShelter)
	var i Shelter
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.LegalName,
		&i.DisplayName,
		&i.Country,
		&i.State,
		&i.City,
		&i.Status,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Mission,
		&i.Vision,
		&i.About,
		&i.LogoMediaID,
		&i.CoverMediaID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Website,
		&i.Socials,
		&i.DonationLinks,
		&i.StorageBytesUsed,
		&i.StorageQuotaBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShelterProfile = `-- name: UpdateShelterProfile :execrows
UPDATE shelters
SET display_name = $2,
    mission      = $3,
    vision       = $4,
    about        = $5,
    updated_at   = now()
WHERE id = $1
`

type UpdateShelterProfileParams struct {
	ID          uuid.UUID
	DisplayName string
	Mission     pgtype.Text
	Vision      pgtype.Text
	About       pgtype.Text
}

// The institutional profile of §4.1. `execrows` rather than `exec`: a policy
// that filtered the row away reports zero rows, and callers have to be able to
// tell that apart from a successful write.
func (q *Queries) UpdateShelterProfile(ctx context.Context, arg UpdateShelterProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateShelterProfile,
		arg.ID,
		arg.DisplayName,
		arg.Mission,
		arg.Vision,
		arg.About,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
