// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, password_hash, full_name, phone, status, email_verified_at, totp_secret_enc, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

// Users and memberships.
//
// `users` is the one table in this schema that belongs to no shelter (D6), so
// its visibility comes from a policy that reads `memberships` and, since 00009,
// `adoption_applications`. A caller sees exactly the users those two branches
// allow — nothing here narrows it further.
// `email` is `citext`, so this finds a differently-cased address without the
// call site remembering to normalise (D7).
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inviteMember = `-- name: InviteMember :exec
INSERT INTO memberships (id, user_id, shelter_id, role, status, invited_by)
VALUES ($1, $2, $3, $4, 'invited', $5)
`

type InviteMemberParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ShelterID uuid.UUID
	Role      string
	InvitedBy pgtype.UUID
}

// Supplying `shelter_id` is not filtering by it: the column is NOT NULL and
// `WITH CHECK` is what verifies the value.
func (q *Queries) InviteMember(ctx context.Context, arg InviteMemberParams) error {
	_, err := q.db.Exec(ctx, inviteMember,
		arg.ID,
		arg.UserID,
		arg.ShelterID,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const listShelterMembers = `-- name: ListShelterMembers :many
SELECT users.id, users.email, users.password_hash, users.full_name, users.phone, users.status, users.email_verified_at, users.totp_secret_enc, users.last_login_at, users.created_at, users.updated_at, m.role, m.status
FROM memberships m
JOIN users ON users.id = m.user_id
ORDER BY users.full_name
`

type ListShelterMembersRow struct {
	User   User
	Role   string
	Status string
}

// The staff of the current shelter. `memberships` is tenant-scoped, so the join
// is already narrowed to this tenant without a predicate here.
func (q *Queries) ListShelterMembers(ctx context.Context) ([]ListShelterMembersRow, error) {
	rows, err := q.db.Query(ctx, listShelterMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShelterMembersRow
	for rows.Next() {
		var i ListShelterMembersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Status,
			&i.User.EmailVerifiedAt,
			&i.User.TotpSecretEnc,
			&i.User.LastLoginAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
