/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports that the process is alive. Never touches external systems, so it
         *     stays cheap and cannot be brought down by a dependency outage.
         *
         *     This is the ONLY endpoint a keep-alive cron may target: hitting /readyz
         *     instead would wake the database and burn Neon CU-hours (see ADR-0003).
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Runs every registered dependency check. Returns 503 with the names of
         *     the failing checks so an operator can tell WHICH dependency is down
         *     without reading logs.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "status": "ok"
         *     }
         */
        LivenessStatus: {
            /** @enum {string} */
            status: "ok";
        };
        /**
         * @example {
         *       "status": "ready"
         *     }
         */
        ReadinessStatus: {
            /** @enum {string} */
            status: "ready";
        };
        /**
         * @example {
         *       "status": "not ready",
         *       "failed": [
         *         "postgres"
         *       ]
         *     }
         */
        ReadinessFailure: {
            /** @enum {string} */
            status: "not ready";
            /** @description Names of the dependency checks that failed. */
            failed: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency check passed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description At least one dependency check failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessFailure"];
                };
            };
        };
    };
}
